name: EC2 Random Folder Creator

on:
  workflow_dispatch:

jobs:
  create-folders-files:
    runs-on: self-hosted

    steps:
      - name: Create random folders and files in EC2
        run: |
          BASE_DIR="/home/ubuntu/testdata"
      
          mkdir -p "$BASE_DIR"

          dir1="dir_$(tr -dc a-z0-9 </dev/urandom | head -c6)"
          dir2="dir_$(tr -dc a-z0-9 </dev/urandom | head -c6)"

          mkdir -p "$BASE_DIR/$dir1"
          mkdir -p "$BASE_DIR/$dir2"

          for dir in "$BASE_DIR/$dir1" "$BASE_DIR/$dir2"; do
            for i in {1..2}; do
              file="file_$(tr -dc a-z0-9 </dev/urandom | head -c6).txt"
              echo "This is random content for $dir/$file" > "$dir/$file"
            done
          done
