name: Folder and File Creator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-folders:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create random folders and files
        run: |
          # Generate two random folder names
          FOLDER1="dir_$(head /dev/urandom | tr -dc a-z0-9 | head -c6)"
          FOLDER2="dir_$(head /dev/urandom | tr -dc a-z0-9 | head -c6)"

          echo "Creating folders: $FOLDER1 and $FOLDER2"
          mkdir $FOLDER1 $FOLDER2

          # Create two random files in each folder with random content
          for FOLDER in $FOLDER1 $FOLDER2; do
            for i in 1 2; do
              FILE="$FOLDER/file_$(head /dev/urandom | tr -dc a-z0-9 | head -c6).txt"
              echo "This is random content for $FILE" > $FILE
              echo "Created $FILE with content:"
              cat $FILE
              echo "-----------------------------"
            done
          done

      - name: List all created files
        run: ls -R
